# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 38276e3d2bd85ff372219de3788fb2312d5e84072876de9e12884c5e896024aa555d60210f1b23f04332c3eeeabf49bd7ed131ac43d24d12230b35911bf2520b

test:
  secret_key_base: c420ec774b1a68275b57fad7afde40c008403f1c804355167da4fa779e04fc19940cd117c5cf902934ac82896f6e8bc6970933163dc522cb491e02f1bf7ac43c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
